name: Run Tests 🧪

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  theme-tests:
    uses: pressbooks/reusable-workflows/.github/workflows/pb-plugin-tests.yml@main
    secrets: inherit
    with:
      requires_pressbooks: false
      use_mariadb: false
  trigger_bedrock_updates:
    needs: theme-tests
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Bedrock Updates
        if: github.ref == 'refs/heads/dev'
        uses: pressbooks/composer-autoupdate-bedrock@main
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SNS_ARN_DEV: ${{ secrets.AWS_SNS_ARN_DEV }}
          AWS_SNS_ARN_STAGING: ${{ secrets.AWS_SNS_ARN_STAGING }}
          INPUT_TRIGGERED_BY: ${{ github.repository }}
          REF: ${{ github.ref }}
