name: Update POT file

on:
  push:
    branches:
    - dev
    paths:
    - '**.php'
    - '**.js'
  workflow_dispatch:

jobs:
  update-pot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP with tools
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: composer, wp-cli/wp-cli-bundle
    - name: Update POT file
      run: wp i18n make-pot . languages/pressbooks-aldine.pot --domain=pressbooks-aldine --slug=pressbooks-aldine --package-name="Aldine" --headers="{\"Report-Msgid-Bugs-To\":\"https://github.com/pressbooks/pressbooks-aldine/issues\"}"
    - name: Commit updated POT file
      uses: stefanzweifel/git-auto-commit-action@v4.15.4
      with:
        commit_message: 'chore(l10n): update languages/pressbooks-aldine.pot'
        file_pattern: '*.pot'
